# Generated by Django 4.2.6 on 2024-01-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_username'),
        ('main', '0002_articles_author'),
    ]

    operations = [
    ]
