# Generated by Django 4.2.6 on 2024-01-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comments_articel_alter_comments_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.AlterField(
            model_name='comments',
            name='articel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articles'),
        ),
    ]
