# Generated by Django 4.2.6 on 2024-01-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_comments_author_alter_comments_articel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='articel',
            new_name='article',
        ),
    ]
